<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Menghapus semua data produk dan mereset ID
        Product::truncate();

        // Data produk yang akan di-seed
        $products = [
            [
                'name' => 'Premium Real Estate Landing Page',
                'slug' => 'premium-real-estate-landing',
                'description' => 'Modern and elegant landing page template for real estate business.',
                'price' => 299000,
                'discount_price' => 199000,
                'image' => 'https://themewagon.com/wp-content/uploads/2020/12/eflyer.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'E-Learning Platform Template',
                'slug' => 'e-learning-platform',
                'description' => 'Complete e-learning platform with course listings, instructor profiles, and student dashboard.',
                'price' => 499000,
                'discount_price' => 349000,
                'image' => 'https://s3-alpha.figma.com/hub/file/5854097271/1922d9d6-aeaa-400d-82d3-697e040752dc-cover.png',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => false,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Business Portfolio Website Template',
                'slug' => 'business-portfolio-website',
                'description' => 'A sleek and professional portfolio template for showcasing business services.',
                'price' => 159000,
                'discount_price' => 119000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/148200/metorik-business-consulting-html5-website-template_148256-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => true,
                'category_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Photography Portfolio Template',
                'slug' => 'photography-portfolio',
                'description' => 'Elegant portfolio template designed for professional photographers to showcase their work.',
                'price' => 249000,
                'discount_price' => 179000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/195400/fiona-photography-portfolio-html5-website-template_195406-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Corporate Business Template',
                'slug' => 'corporate-business-template',
                'description' => 'A corporate website template with a clean and professional design suitable for businesses.',
                'price' => 399000,
                'discount_price' => 299000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/203400/oxence-multipurpose-business-html5-website-template_203433-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => false,
                'category_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Startup Landing Page Template',
                'slug' => 'startup-landing-page',
                'description' => 'A modern and interactive landing page template designed for startups to showcase their products.',
                'price' => 199000,
                'discount_price' => 149000,
                'image' => 'https://s3-figma-hubfile-images-production.figma.com/hub/file/carousel/img/04f6e23d1c45f4ff4c71244234e62baa335450a1',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Blog and News Website Template',
                'slug' => 'blog-news-website',
                'description' => 'A clean and user-friendly template for blog or news websites with multiple layouts.',
                'price' => 129000,
                'discount_price' => 99900,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/164400/newsgency-blog-news-magazine-html5-template_164418-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => false,
                'category_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Restaurant & Cafe Template',
                'slug' => 'restaurant-cafe-template',
                'description' => 'Beautiful template for restaurants and cafes with menu showcase and online reservation system.',
                'price' => 179000,
                'discount_price' => 139000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/210200/khadyo-restaurant-html5-website-template_210224-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fitness & Gym Website Template',
                'slug' => 'fitness-gym-template',
                'description' => 'Dynamic and energetic template for fitness centers and gyms with class schedules.',
                'price' => 219000,
                'discount_price' => 169000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/148900/powergym-gym-fitness-html5-template_148999-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => true,
                'category_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Travel Agency Template',
                'slug' => 'travel-agency-template',
                'description' => 'Stunning template for travel agencies with tour packages and booking features.',
                'price' => 329000,
                'discount_price' => 249000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/214200/travio-travel-tour-booking-html5-template_214266-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => false,
                'category_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fashion E-commerce Template',
                'slug' => 'fashion-ecommerce-template',
                'description' => 'Stylish e-commerce template for fashion stores with product catalog and shopping cart.',
                'price' => 449000,
                'discount_price' => 349000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/203900/saka-fashion-ecommerce-html5-template_203924-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Medical & Healthcare Template',
                'slug' => 'medical-healthcare-template',
                'description' => 'Professional template for medical practices and healthcare providers.',
                'price' => 379000,
                'discount_price' => 289000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/194400/doccure-medical-healthcare-template_194488-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => false,
                'category_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Creative Agency Template',
                'slug' => 'creative-agency-template',
                'description' => 'Bold and creative template for design agencies and creative studios.',
                'price' => 299000,
                'discount_price' => 229000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/367200/imal-creative-agency-business-services-modern-website-template_367217-3-original.png',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Music & Event Template',
                'slug' => 'music-event-template',
                'description' => 'Vibrant template for musicians, bands, and event organizers.',
                'price' => 189000,
                'discount_price' => 149000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/152200/eventiz-event-conference-html5-template_152274-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => true,
                'category_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tech Startup SaaS Template',
                'slug' => 'tech-startup-saas-template',
                'description' => 'Modern SaaS template for tech startups with pricing tables and feature showcase.',
                'price' => 549000,
                'discount_price' => 429000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/216800/saasbox-software-saas-product-html5-landing-page-template_216803-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Architecture & Interior Design Template',
                'slug' => 'architecture-interior-design-template',
                'description' => 'Sophisticated template for architects and interior designers to showcase projects.',
                'price' => 269000,
                'discount_price' => 199000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/194600/architronix-architecture-interior-html5-template_194647-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => false,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert products into the database
        Product::insert($products);
    }
}