<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Menghapus semua data produk dan mereset ID
        Product::truncate();

        // Data produk yang akan di-seed
        $products = [
            [
                'name' => 'Premium Real Estate Landing Page',
                'slug' => 'premium-real-estate-landing',
                'description' => 'Modern and elegant landing page template for real estate business.',
                'price' => 299000,
                'discount_price' => 199000,
                'image' => 'https://themewagon.com/wp-content/uploads/2020/12/eflyer.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'E-Learning Platform Template',
                'slug' => 'e-learning-platform',
                'description' => 'Complete e-learning platform with course listings, instructor profiles, and student dashboard.',
                'price' => 499000,
                'discount_price' => 349000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/446000/craftx-creative-agency-html5-template_446025-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => false,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Business Portfolio Website Template',
                'slug' => 'business-portfolio-website',
                'description' => 'A sleek and professional portfolio template for showcasing business services.',
                'price' => 159000,
                'discount_price' => 119000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/148200/metorik-business-consulting-html5-website-template_148256-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => true,
                'category_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Photography Portfolio Template',
                'slug' => 'photography-portfolio',
                'description' => 'Elegant portfolio template designed for professional photographers to showcase their work.',
                'price' => 249000,
                'discount_price' => 179000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/195400/fiona-photography-portfolio-html5-website-template_195406-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Corporate Business Template',
                'slug' => 'corporate-business-template',
                'description' => 'A corporate website template with a clean and professional design suitable for businesses.',
                'price' => 399000,
                'discount_price' => 299000,
                'image' => 'https://w3layouts.b-cdn.net//wp-content/uploads/2020/05/sprystore-website-template-scaled.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => false,
                'category_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Startup Landing Page Template',
                'slug' => 'startup-landing-page',
                'description' => 'A modern and interactive landing page template designed for startups to showcase their products.',
                'price' => 199000,
                'discount_price' => 149000,
                'image' => 'https://themefisher.com/blog/kallyas.webp',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Blog and News Website Template',
                'slug' => 'blog-news-website',
                'description' => 'A clean and user-friendly template for blog or news websites with multiple layouts.',
                'price' => 129000,
                'discount_price' => 99900,
                'image' => 'https://htmlcodex.com/wp-content/uploads/2021/07/startup-website-template.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => false,
                'category_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Restaurant & Cafe Template',
                'slug' => 'restaurant-cafe-template',
                'description' => 'Beautiful template for restaurants and cafes with menu showcase and online reservation system.',
                'price' => 179000,
                'discount_price' => 139000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/47600/grocmart-grocery-store-multipage-classic-html-website-template_47684-3-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fitness & Gym Website Template',
                'slug' => 'fitness-gym-template',
                'description' => 'Dynamic and energetic template for fitness centers and gyms with class schedules.',
                'price' => 219000,
                'discount_price' => 169000,
                'image' => 'https://w3layouts.b-cdn.net//wp-content/uploads/2023/04/UI-Portfolio-Website-Template-scaled-1.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => true,
                'category_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Travel Agency Template',
                'slug' => 'travel-agency-template',
                'description' => 'Stunning template for travel agencies with tour packages and booking features.',
                'price' => 329000,
                'discount_price' => 249000,
                'image' => 'https://uicreative.s3.ap-southeast-1.amazonaws.com/wp-content/uploads/2021/03/03010617/auto-draft-123.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => false,
                'category_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Fashion E-commerce Template',
                'slug' => 'fashion-ecommerce-template',
                'description' => 'Stylish e-commerce template for fashion stores with product catalog and shopping cart.',
                'price' => 449000,
                'discount_price' => 349000,
                'image' => 'https://uicreative.s3.ap-southeast-1.amazonaws.com/wp-content/uploads/2021/03/03010701/auto-draft-126-1024x683.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Medical & Healthcare Template',
                'slug' => 'medical-healthcare-template',
                'description' => 'Professional template for medical practices and healthcare providers.',
                'price' => 379000,
                'discount_price' => 289000,
                'image' => 'https://w3layouts.b-cdn.net//wp-content/uploads/2020/09/factory-website-template-scaled.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => false,
                'category_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Creative Agency Template',
                'slug' => 'creative-agency-template',
                'description' => 'Bold and creative template for design agencies and creative studios.',
                'price' => 299000,
                'discount_price' => 229000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/367200/imal-creative-agency-business-services-modern-website-template_367217-3-original.png',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Music & Event Template',
                'slug' => 'music-event-template',
                'description' => 'Vibrant template for musicians, bands, and event organizers.',
                'price' => 189000,
                'discount_price' => 149000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/152200/eventiz-event-conference-html5-template_152274-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => true,
                'category_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tech Startup SaaS Template',
                'slug' => 'tech-startup-saas-template',
                'description' => 'Modern SaaS template for tech startups with pricing tables and feature showcase.',
                'price' => 549000,
                'discount_price' => 429000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/216800/saasbox-software-saas-product-html5-landing-page-template_216803-original.jpg',
                'preview_url' => '#',
                'is_featured' => true,
                'is_new' => true,
                'category_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Architecture & Interior Design Template',
                'slug' => 'architecture-interior-design-template',
                'description' => 'Sophisticated template for architects and interior designers to showcase projects.',
                'price' => 269000,
                'discount_price' => 199000,
                'image' => 'https://s.tmimgcdn.com/scr/800x500/194600/architronix-architecture-interior-html5-template_194647-original.jpg',
                'preview_url' => '#',
                'is_featured' => false,
                'is_new' => false,
                'category_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert products into the database
        Product::insert($products);
    }
}