<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Menghapus semua data produk dan mereset ID
        Product::truncate();

        // Data produk yang akan di-seed
        $products = [
    [
        'name' => 'Premium Real Estate Landing Page',
        'slug' => 'premium-real-estate-landing',
        'description' => 'Modern and elegant landing page template for real estate business.',
        'price' => 299000,
        'discount_price' => 199000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff0000?text=Real+Estate',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => true,
        'category_id' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'E-Learning Platform Template',
        'slug' => 'e-learning-platform',
        'description' => 'Complete e-learning platform with course listings, instructor profiles, and student dashboard.',
        'price' => 499000,
        'discount_price' => 349000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff0000?text=E-Learning',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => false,
        'category_id' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Business Portfolio Website Template',
        'slug' => 'business-portfolio-website',
        'description' => 'A sleek and professional portfolio template for showcasing business services.',
        'price' => 159000,
        'discount_price' => 119000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff6600?text=Business+Portfolio',
        'preview_url' => '#',
        'is_featured' => false,
        'is_new' => true,
        'category_id' => 2,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Photography Portfolio Template',
        'slug' => 'photography-portfolio',
        'description' => 'Elegant portfolio template designed for professional photographers to showcase their work.',
        'price' => 249000,
        'discount_price' => 179000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff00cc?text=Photography+Portfolio',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => true,
        'category_id' => 3,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Corporate Business Template',
        'slug' => 'corporate-business-template',
        'description' => 'A corporate website template with a clean and professional design suitable for businesses.',
        'price' => 399000,
        'discount_price' => 299000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/00cc00?text=Corporate+Business',
        'preview_url' => '#',
        'is_featured' => false,
        'is_new' => false,
        'category_id' => 4,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Startup Landing Page Template',
        'slug' => 'startup-landing-page',
        'description' => 'A modern and interactive landing page template designed for startups to showcase their products.',
        'price' => 199000,
        'discount_price' => 149000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/00ffcc?text=Startup+Landing',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => true,
        'category_id' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Blog and News Website Template',
        'slug' => 'blog-news-website',
        'description' => 'A clean and user-friendly template for blog or news websites with multiple layouts.',
        'price' => 129000,
        'discount_price' => 99900,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/0000ff?text=Blog+News',
        'preview_url' => '#',
        'is_featured' => false,
        'is_new' => false,
        'category_id' => 5,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'App Landing Page Template',
        'slug' => 'app-landing-page',
        'description' => 'Landing page template for mobile app showcasing features, pricing, and call-to-action.',
        'price' => 169000,
        'discount_price' => 119000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/00ff00?text=App+Landing',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => true,
        'category_id' => 6,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Online Store Template',
        'slug' => 'online-store-template',
        'description' => 'E-commerce website template for building a sleek online store with product listings.',
        'price' => 399000,
        'discount_price' => 299000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff0000?text=Online+Store',
        'preview_url' => '#',
        'is_featured' => false,
        'is_new' => false,
        'category_id' => 7,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Fashion Store Template',
        'slug' => 'fashion-store-template',
        'description' => 'Elegant and modern template for fashion stores to showcase clothing and accessories.',
        'price' => 299000,
        'discount_price' => 199000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ffcc00?text=Fashion+Store',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => false,
        'category_id' => 7,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Tech Startup Template',
        'slug' => 'tech-startup-template',
        'description' => 'A high-tech template perfect for showcasing technology startups and apps.',
        'price' => 229000,
        'discount_price' => 169000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/008000?text=Tech+Startup',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => true,
        'category_id' => 1,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Food Delivery Service Template',
        'slug' => 'food-delivery-service-template',
        'description' => 'A dynamic website template designed for food delivery services, with modern features.',
        'price' => 199000,
        'discount_price' => 149000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff6600?text=Food+Delivery',
        'preview_url' => '#',
        'is_featured' => false,
        'is_new' => false,
        'category_id' => 5,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Non-Profit Organization Template',
        'slug' => 'non-profit-organization-template',
        'description' => 'Template designed for non-profit organizations, with donation integration and event management.',
        'price' => 179000,
        'discount_price' => 129000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/cc0099?text=Non-Profit',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => false,
        'category_id' => 3,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Real Estate Agent Template',
        'slug' => 'real-estate-agent-template',
        'description' => 'Professional real estate agent template with property listings and contact features.',
        'price' => 299000,
        'discount_price' => 229000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff0000?text=Real+Estate+Agent',
        'preview_url' => '#',
        'is_featured' => false,
        'is_new' => true,
        'category_id' => 2,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Spa and Wellness Template',
        'slug' => 'spa-wellness-template',
        'description' => 'A soothing and calming template for spa and wellness services.',
        'price' => 219000,
        'discount_price' => 159000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff00ff?text=Spa+Wellness',
        'preview_url' => '#',
        'is_featured' => true,
        'is_new' => true,
        'category_id' => 6,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'name' => 'Event and Conference Template',
        'slug' => 'event-conference-template',
        'description' => 'Perfect template for events and conferences with registration and agenda features.',
        'price' => 239000,
        'discount_price' => 189000,
        'image' => 'https://via.placeholder.com/400x300/1a1a1a/ff0000?text=Event+Conference',
        'preview_url' => '#',
        'is_featured' => false,
        'is_new' => false,
        'category_id' => 5,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ]
];


        // Menggunakan insert untuk memasukkan data produk sekaligus
        Product::insert($products);
    }
}
